#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source zplug
if [[ -s ~/.zplug/init.zsh ]]; then
  source ~/.zplug/init.zsh
fi

if [[ -s /usr/share/zsh/scripts/zplug/init.zsh ]]; then
  source /usr/share/zsh/scripts/zplug/init.zsh
fi

# Source Wyplay variables
if [[ -s ~/.genbox_env ]]; then
  source ~/.genbox_env
fi

autoload -Uz compinit

# Customize to your needs...
#alias genbox="echo sudo /media/lchopin/hdd/genbox/bin/genbox-ng -v"
alias genbox="echo sudo /home/lchopin/genbox/bin/genbox-ng -v /usr/sbin/sshd"
alias genbox_canal="echo sudo /home/lchopin/genbox_canal/bin/genbox-ng -v"
alias chroot-android="echo 'sudo mount --bind /tftpboot /home/lchopin/opt/ubundroid/remaster-root/tftpboot; sudo mount --bind /media/lchopin/hdd /home/lchopin/opt/ubundroid/remaster-root/media/; export HOME=/root/; sudo uck-remaster-chroot-rootfs /home/lchopin/opt/ubundroid/'"
alias picocom0="picocom --nolock --databits 8 --baud 115200 /dev/ttyUSB0"
alias picocom1="picocom --nolock --databits 8 --baud 115200 /dev/ttyUSB1"
alias picocom2="picocom --nolock --databits 8 --baud 115200 /dev/ttyUSB2"
alias minicom0="minicom --wrap --color=on --noinit --baudrate 115200 --device /dev/ttyUSB0"
alias minicom1="minicom --wrap --color=on --noinit --baudrate 115200 --device /dev/ttyUSB1"
alias cls="echo -ne '\033c'"
alias cur_track="qdbus org.mpris.MediaPlayer2.clementine /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get org.mpris.MediaPlayer2.Player Metadata"
alias reboot="echo no, not here!"
alias -g G='| grep'
alias -g L='| less'
alias -g F='| fzf'
alias aptitude='nocorrect aptitude' # no spelling correction on aptitude
alias j='jobs'
alias tee="tee -a"
alias tm="tmux attach || tmux new"
alias ag="ag -S" # Smart search
alias vi="vim"
# https://coderwall.com/p/lyrjsq/extract-your-external-ip-using-command-line-tools
alias ip_ext='curl -s monip.org | sed -n "s#.*IP : \([0-9.]*\).*#\1\n#p"'
alias myip='curl -s https://api.myip.com | jq -r .ip'
alias gbp='git rev-parse --abbrev-ref HEAD'
alias tiga="tig --all"
alias tigs="tig status"
alias fzf="fzf --multi --reverse"
alias eopen="~/bin/eclipse --launcher.openFile $PWD/"
alias sshg="ssh  \$(basename \$(readlink ~/genbox))"
alias pf="fzf --preview='bat --color=always {}'"
alias gcob='git branch | fzf | xargs git checkout'
alias diff='diff --color=auto'
alias ip='ip -color=auto'
alias qrr='scrot --select --overwrite /dev/stdout | zbarimg /dev/stdin'

# 10 second wait if you do something that will delete everything. I wish I'd had this before...
setopt RM_STAR_WAIT

# Traite les liens symbolique comme il faut
#setopt chase_links

# find from name in current directory
function ff() { find . -type f -iname \*${*}\* -ls ; }

# generate a dated .bak from file
function bak() { cp $1 $1_`date +%Y-%m-%d_%H-%M-%S`.bak ; }

function report_local_port_forwardings() {

  # -a ands the selection criteria (default is or)
  # -i4 -i6 limits to ipv4 and ipv6 internet files
  # -P inhibits the conversion of port numbers to port names
  # -c /regex/ limits to commands matching the regex
  # -u$USER limits to processes owned by $USER
  # http://man7.org/linux/man-pages/man8/lsof.8.html
  # https://stackoverflow.com/q/34032299

  echo
  echo "LOCAL PORT FORWARDING"
  echo
  echo "You set up the following local port forwardings:"
  echo

  lsof -a -i4 -i6 -P -c '/^ssh$/' -u$USER -s TCP:LISTEN

  echo
  echo "The processes that set up these forwardings are:"
  echo

  ps -f -p $(lsof -t -a -i4 -P -c '/^ssh$/' -u$USER -s TCP:LISTEN)

}


bindkey '\e[1~'   beginning-of-line  # Linux console
bindkey '\e[H'    beginning-of-line  # xterm
bindkey '\eOH'    beginning-of-line  # gnome-terminal
bindkey '\e[2~'   overwrite-mode     # Linux console, xterm, gnome-terminal
bindkey '\e[3~'   delete-char        # Linux console, xterm, gnome-terminal
bindkey '\e[4~'   end-of-line        # Linux console
bindkey '\e[F'    end-of-line        # xterm
bindkey '\eOF'    end-of-line        # gnome-terminal

export QT_X11_NO_MITSHM=1 # needed by kdiff3 for root user
export GENBOX_ROOT=/home/lchopin/genbox/targets/current/root

zplug "junegunn/fzf", as:command, hook-build:"./install --bin", use:"bin/{fzf-tmux,fzf}"
# fzf
export FZF_DEFAULT_COMMAND='fd --type f --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
#export FZF_DEFAULT_OPTS='--preview "bat --style=numbers --color=always --line-range :500 {}"'
export FZF_DEFAULT_OPTS='--preview "less {}"'
source ~/.zplug/repos/junegunn/fzf/shell/key-bindings.zsh
source ~/.zplug/repos/junegunn/fzf/shell/completion.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
