#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#alias genbox="echo sudo /media/lchopin/hdd/genbox/bin/genbox-ng -v"
alias genbox="echo sudo /home/lchopin/genbox/bin/genbox-ng -v"
alias chroot-android="echo 'sudo mount --bind /tftpboot /home/lchopin/opt/ubundroid/remaster-root/tftpboot; sudo mount --bind /media/lchopin/hdd /home/lchopin/opt/ubundroid/remaster-root/media/; export HOME=/root/; sudo uck-remaster-chroot-rootfs /home/lchopin/opt/ubundroid/'"
alias picocom0="picocom --nolock --baud 115200 /dev/ttyUSB0"
alias picocom1="picocom --nolock --baud 115200 /dev/ttyUSB1"
alias picocom2="picocom --nolock --baud 115200 /dev/ttyUSB2"
alias cls="echo -ne '\033c'"
alias cur_track="qdbus org.mpris.clementine /Player "org.freedesktop.MediaPlayer.GetMetadata""
alias reboot="echo no, not here!"
alias -g G='| grep'
alias aptitude='nocorrect aptitude' # no spelling correction on aptitude
alias j='jobs'
alias tee="tee -a"
alias tm="tmux attach || tmux new"
alias ag="ag -S" # Smart search
alias vi="vim"
# https://coderwall.com/p/lyrjsq/extract-your-external-ip-using-command-line-tools
alias ip_ext="curl -s monip.org | sed -n 's#.*IP : \([0-9.]*\).*#\1\n#p'"

# 10 second wait if you do something that will delete everything. I wish I'd had this before...
setopt RM_STAR_WAIT

# Traite les liens symbolique comme il faut
#setopt chase_links

# find from name in current directory
function ff() { find . -type f -iname \*${*}\* -ls ; }

# generate a dated .bak from file
function bak() { cp $1 $1_`date +%Y-%m-%d_%H-%M-%S`.bak ; }

